# These are supported funding model platforms

github: yourusername # Replace with your GitHub handle
patreon: yourusername # Replace with your Patreon handle
kofi: yourusername
custom: ["https://yourcustomwebsite.com/purchase-commercial-license"]
